const insultList = [
  "juntti",
  "tyhmä",
  "hullu",
  "sika",
  "huora",
  "homo",
  "paskapää",
  "läski",
  "nynny",
  "runkkari",
  "eunukinperse",
  "känsärunkku",
  "kyrpäyrjö",
  "sturtsireva",
  "luuskapillu",
  "gulashi",
  "idiootti",
  "imbesilli",
  "kökkötraktori",
  "lahtari",
  "luuseri",
  "nojatuolikernaali",
  "peelo",
  "suvakki",
  "soijapoika",
  "autisti",
  "sinappipökäle",
  "hönö",
  "masentava tapa elävää",
  "kusipää",
  "persviiksi",
  "rotta",
  "kelarotta",
  "kusilinko",
  "pieruperse",
  "miekkaperse",
  "kärpärunkku",
  "ruma",
  "hunsvotti",
  "huoranmetsästäjä",
  "kusimuhlu",
  "kaakinpuuhuora",
  "kiukkuvittu",
  "tohlopeukalo",
  "kurmukerttu",
  "mokomakin ostrogootti saksiravun ektoplasma",
  "torvijalka",
  "käärme",
  "suonitupponen",
  "torakka",
  "siittiö",
  "paska",
  "järkyttävän paska",
  "setämies",
  "herneaivoinen heinäseiväs",
  "killisilmäiset kiusankappaleet",
  "kumiaivoiset kuraläpät",
  "kuolaava kumisilmä",
  "lusmuileva luumu",
  "pahviaivoinen palsternakka",
  "rajoitteinen rapa-aivoinen rasvaimu",
  "seniili seinäruusu",
  "taliaivoinen tamburiini",
  "ruski",
  "kiinalainen",
  "ruotsalainen",
  "juutalainen",
  "turkulainen",
  "mikkeliläinen",
  "sappikivi",
  "kansalainen",
  "pyrstömolva",
  "stupid",
  "äpärä",
  "sossupummi",
  "sketsiobjekti",
  "kompostikaali",
  "nakki",
  "komposti",
  "impotentti",
  "ongelmajätettä",
  "roska",
  "ydinjätettä",
  "persu",
  "väinö",
  "alfabeetikko",
  "säkki",
  "pers-ihminen",
  "Einen ainut aivosolu",
  "työtön",
  "kullinmutka",
  "kusirako",
  "keravalainen",
  "vittupää",
  "suusta hengittävä evoluution hukkapala",
  "käsienheiluttelija",
  "tyhmä",
  "ameba",
  "ruomakulli",
  "limane vittusaatana",
  "kyrpähomo",
  "kyrvänsyylä",
  "kyrväke",
  "paviaani",
  "lukihäiriöinen paska",
  "vajaa",
  "mutsis",
  "helari",
  "näätä",
  "spandex-pelle",
  "hihhuli",
  "Remove Kebab",
  "karvakäsi",
  "manne",
  "hurri",
  "turri",
  "Warmduscher",
  "varjoon pysäköijä",
  "sääennusteiden lueskelija",
  "kevytkenkäinen",
  "lutka",
  "äitis",
  "niilon vasen jalka",
  "hampaaton läski",
  "neitsyt",
  "eeddspeaks",
  "sosiopaatti",
  "psykopaatti",
  "nisti",
  "vitsi",
  "peruna",
  "paskakasa",
  "ilmaa",
  "nuubi",
  "masentunu kasa paskaa",
  "Hukan average vieweriä alempiarvoisempi muhlu",
  "narkkari",
  "incel",
  "koira",
  "kusipää kala",
  "kyrpä",
  "kyrpärunkku",
  "weebo",
  "gonahtanut",
  "apian",
  "naapuri",
  "valkoroska",
  "pepega",
  "läski",
  "hiekkapillu",
  "natsi",
  "femakko",
  "kana",
  "pöljä",
  "juoppo koditon",
  "protoplasma",
  "juoppo",
  "koditon",
  "terveysintoilija",
  "verkostomarkkinoija",
  "analfabeetti",
  "fagotti",
  "blondi",
  "anakronismin multihuipentuma",
  "plösö",
  "luumukiisselillä täytetty spurgu",
  "spurgu",
  "pilluintiaani",
  "mankeli",
  "rotanruokaa",
  "sosiaalidemokraatti",
  "imurihuora",
  "vihervassari",
  "uusnatsi",
  "punkero",
  "kommunisti",
  "hikipinko",
  "spede",
  "tuhkamuna",
  "tissiposki",
  "punapersepaviaani",
  "keltanokka",
  "vajokki",
  "retardi",
  "hinuri",
  "saasta",
  "nyyppä",
  "salaatin väärinkäyttäjä",
  "säälittävä",
  "epätoivoinen",
  "homo vittu",
  "kakkapää",
  "sekopää",
  "nivushiertymä",
  "beta",
  "simp",
  "alalauteillaistuja",
  "somali",
  "rasisti",
  "rico187",
  "nyymi",
  "aivokääpiö",
  "kääpiö",
  "midgetti",
  "lyhytkasvuinen",
  "vajakki",
  "jälkeenjäänyt",
  "mitätön",
  "puliukko",
  "pullukka",
  "aasi",
  "musta",
  "häntäheikki",
  "kännissä",
  "kummelihahmo",
  "Elisan liittymämyyjä",
];

exports.sendInsult = async (client) => {
  // const channel = client.channels.cache.get("689462403658022932");
  const channel = await client.channels.fetch("884404862991859725"); // test channel

  const list = insultList.filter(function (a, i) {
    return insultList.indexOf(a) == i;
  });
  const insult = list[Math.floor(Math.random() * list.length)];

  if (Math.random() < 0.15) {
    channel.send("<@154252681949478912> on vitun " + insult + "!");
  } else {
    channel.send("<@154252681949478912> on " + insult + "!");
  }
};
